apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user_service.fullname" . }}
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
data:
  {{- if .Values.django.debug }}
  DEBUG: "true"
  {{- end }}