apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "user_service.fullname" . }}
  labels:
    {{- include "user_service.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nslookup {{ include "postgresql.fullname" . }}; do echo waiting for db; sleep 2; done;' ]
      containers:
      - name: django-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
          - sh
          - "-c"
          - python3 manage.py migrate
        env:
          - name: DB_DSN
            valueFrom:
              secretKeyRef:
                name: {{ include "user_service.fullname" . }}
                key: DB_DSN
          - name: DJANGO_SETTINGS_MODULE
            value: "user_service.settings"
      restartPolicy: Never
  backoffLimit: 1