apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-ingress-microk8s-controller
  namespace: ingress
  labels:
    microk8s-application: nginx-ingress-microk8s
    release: prometheus
spec:
  selector:
    matchLabels:
      name: nginx-ingress-microk8s
  podMetricsEndpoints:
  - port: health
    interval: 15s